version: '3'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host  

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my
      POSTGRES_DB: health_record
    volumes:
      - data:/var/lib/postgresql/data 
    network_mode: host  

volumes:
  data:  